Commands.Register("potcfdk", function(message, words) 
	message:Reply("he's alright")
end, "Uh", "")
Commands.Register("katie", function(message, words) 
	message:Reply("She brings the sex in sexy") 
end, "Uh", "")
Commands.Register("suchipi", function(message, words) 
	message:Reply("shhh shes the best") 
end, "Uh", "")